### ISSUE TITLE
Module 12

### ISSUE THREAD

**Issue by hugh-emerson** [abedford/DevOps-Course-Starter#39]
Your M12 work is already merged, and there are a couple of different M12 PRs... so I'm putting my review for M12 here so it's visible.

Generally looks good, but you've leaked credentials.

- OAUTH_CLIENT_SECRET is currently hardcoded in your main.tf instead of being passed in as a variable.
- Your cd_webhook output in outputs.tf should have "sensitive = true" to prevent it appearing in CI/CD logs after terraform apply completes. It contains a password.

**Comment by abedford** [comment]
Hi, I have resolved this in both module 12 and module 13 now.

**Comment by abedford** [comment]
https://github.com/abedford/DevOps-Course-Starter/pull/40
